// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bsnsNiche.Data;

#nullable disable

namespace bsnsNiche.Migrations
{
    [DbContext(typeof(bsnsNicheContext))]
    [Migration("20230906132203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bsnsNiche.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_Id"));

                    b.Property<string>("Account_Assignment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Account_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount_Accepted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount_Accepted_Original_Currency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount_Invoiced")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount_Invoiced_Original_Currency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount_Reconciled")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount_Reconciled_Original_Currency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Article_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Asset_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bill_To_Location_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Budget_Account_Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Budget_Internal_Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Closed_Order_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commodity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commodity_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commodity_ID_L1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commodity_ID_L2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commodity_ID_L3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commodity_L1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commodity_L2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commodity_L3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cost_Center")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cost_Center_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Commodity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Commodity_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Supplier_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Internal_Order_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Is_PunchOut_Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Is_Retroactive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Is_Subcontractor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line_Closed_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Load_Create_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Load_Update_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Need_By_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number_BackOrdered_OC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number_Confirmed_With_Changes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number_Substituted_OC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Confirmation_Status_Header")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Confirmation_Status_Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ordered_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Original_Currency_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Originating_System")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Originating_System_Line_Number")
                        .HasColumnType("int");

                    b.Property<string>("Originating_System_Reference_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PO_Line_Amount_Range_Maximum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PO_Line_Amount_Range_Minimum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PO_Line_Number")
                        .HasColumnType("int");

                    b.Property<decimal>("PO_Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PO_Spend")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PO_Spend_Original_Currency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PO_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_Terms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price_Unit_Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Price_Unit_of_Measure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profit_Center")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profit_Center_ID_Reporting")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receipt_Based_Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiving_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requires_Service_Sheet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Retroactive_Effective_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Routing_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service_Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ship_To_Location_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_System")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_System_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spot_Buy_Marketplace_Seller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_VAT_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tax_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax_Amount_Invoiced")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Unit_Conversion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("buyerVatID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Order_Id");

                    b.ToTable("PurchaseOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
